title: juegosgratis
description: 'Descarga tus juegos gratis :D'
template:
  repo: juegosgratis-template
  name: juegosgratis
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
